### ISSUE TITLE
Mock SSM or provide defaults for offline testing?

### ISSUE THREAD

**Issue by charlie-s** [tallpants/ssm-parameter-store#3]
First, this module fits the bill quite nicely. It automates what we've had to do manually in Lambdas for a while now – using SSM, dealing with async loading, caching results, all with a very simple and consistent usage:

```
const params = new SSMParameterStore(new AWS.SSM(), {
  apiHost: '/NS/API/HOST',
  apiToken: '/NS/API/LAMBDA_X_TOKEN'
})

module.exports.handler = async event => {
  const { apiHost, apiToken } = await params.getAll()
  ... lambda ...
```

I've not run into this particular issue yet because we use separate accounts for dev/staging/prod/etc, and when we're developing we want our local Lambdas to use other dev AWS resources (including SSM parameters). However, is there any decent approach to bypassing / mocking / setting default values for SSM when I want to bypass AWS completely? For example, testing a lambda offline or using a value that's not what's in SSM? (e.g. a local database host instead of the SSM/AWS dev database host). For now I can comment out the SSMParameterStore manually, but occasionally this would come in handy without having to alter the code. Open to suggestions.

**Comment by tallpants** [comment]
1. I think it'd be useful to have a way to define fallback values if a key doesn't exist in SSM, just have to think about what would be a good API for it, maybe something like:

```js
const parameterStore = new SSMParameterStore(new AWS.SSM(), {
  apiHost: ['/NS/API/HOST', 'https://some-fallback-url/endpoint']
});
```

or a more explicit:

```js
const parameterStore = new SSMParameterStore(new AWS.SSM(), {
  apiHost: { key: '/NS/API/HOST', fallbackValue: 'https://some-fallback-url/endpoint' }
});
```

But yea not opposed to adding something like that. However this wouldn't work if you couldn't access AWS at all, only if the key you described wasn't present in AWS. But my guess is the use case for this would be pretty niche. Like it's very unlikely that your AWS account has an SSM key that's present sometimes and absent othertimes. So not sure if this would even be useful.

2. As for bypassing AWS entirely, I don't think that's possible without majorly expanding the scope of the library. Right now it's just a small convenient layer over SSM parameter store whose API is suited for the way most people want SSM parameters to be accessed in Lambdas most of the time. I think if you want to run your lambda locally without connecting to AWS the best thing to do would be to write your own abstraction over this library.

**Comment by tallpants** [comment]
Closing cause no further discussion.
